version: "2.1"
services:
  plate_recognizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plate_recognizer
    volumes:
      - /docker/frigate_plate_recognizer/plates:/plates
      - /docker/frigate_plate_recognizer/config:/config
    restart: unless-stopped
networks: {}
