version: "2.1"
services:
  plate_recognizer:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: plate_recognizer
    volumes:
      - /docker/plate_recognizer/plates:/plates
      - /docker/plate_recognizer/config:/config
    restart: unless-stopped
networks: {}
